prob1: prob1.c prob1_test.c prob1.h evaluation.c evaluation.h
	gcc -g -O0 -Wall -Wextra prob1_test.c prob1.c evaluation.c -o prob1.o
prob2: prob2_test.c prob2.c trie.c prob2.h trie.h
	gcc -g -O0 -Wall -Wextra prob2_test.c prob2.c trie.c -o prob2.o
