main: main.c linked_list.c linked_list.h
	gcc -g -O0 -Wall -Wextra main.c linked_list.c -o main.o
binary_tree: main_binary_tree.c binary_tree.c binary_tree.h
	gcc -g -O0 -Wall -Wextra main_binary_tree.c binary_tree.c -o binary_tree.o
