structs: structs.c structs.h
	gcc -g -O0 -Wall -Wextra structs.c -o structs.o
pointers_to_pointers: pointers_to_pointers.c
	gcc -g -O0 -Wall -Wextra pointers_to_pointers.c -o pointers_to_pointers.o
swap: swap.c swap.h
	gcc -g -O0 -Wall -Wextra swap.c -o swap.o
sort_pointers: sort_pointers.c sort_pointers.h
	gcc -g -O0 -Wall -Wextra sort_pointers.c -o sort_pointers.o
stack_array: stack_array.c stack_array_test.c stack_array.h
	gcc -g -O0 -Wall -Wextra stack_array.c stack_array_test.c -o stack_array.o
