swap: swap.c swap.h
	gcc -g -O0 -Wall -Wextra swap.c -o swap.o
sort_pointers: sort_pointers.c sort_pointers.h
	gcc -g -O0 -Wall -Wextra sort_pointers.c -o sort_pointers.o
stack_array: stack_array.c stack_array_test.c stack_array.h
	gcc -g -O0 -Wall -Wextra stack_array.c stack_array_test.c -o stack_array.o
stack_linked_list: stack_linked_list.c stack_linked_list_test.c stack_linked_list.h
	gcc -g -O0 -Wall -Wextra stack_linked_list.c stack_linked_list_test.c -o stack_linked_list.o
