structs: structs.c structs.h
	gcc -g -O0 -Wall -Wextra structs.c -o structs.o
pointers_to_pointers: pointers_to_pointers.c
	gcc -g -O0 -Wall -Wextra pointers_to_pointers.c -o pointers_to_pointers.o
swap: swap.c swap.h
	gcc -g -O0 -Wall -Wextra swap.c -o swap.o
sort_pointers: sort_pointers.c sort_pointers.h
	gcc -g -O0 -Wall -Wextra sort_pointers.c -o sort_pointers.o
stack: stack.c stack_test.c stack.h
	gcc -g -O0 -Wall -Wextra stack.c stack_test.c -o stack.o
