CFLAGS=-g -O0 -Wall -Wextra
decode: decode_main.c decode.c decode.h
	gcc $(CFLAGS) decode_main.c decode.c -o decode.o
encode: encode_main.c encode.c encode.h
	gcc $(CFLAGS) encode_main.c encode.c -o encode.o
